sauce_connect: true
browsers:
  - name: chrome
    version: latest
  - name: firefox
    version: latest
  - name: safari
    version: latest
  - name: microsoftedge
    version: latest
  - name: iphone
    version: latest
  - name: android
    version: latest
presets:
  local:
    providers: airtap-manual
    browsers:
      - name: manual
browserify:
  - transform: babelify
    global: true
    presets: ['@babel/preset-env']
    plugins: ['@babel/plugin-syntax-import-assertions']
